/zed/zed_driver:
  ros__parameters:
    autostart: true
    base_link_name: base_link
    camera_settings_path: ""
    confidence: 20
    depth_max_distance: 5.0
    depth_min_distance: 0.5
    depth_mode: NEURAL
    depth_rate: 2
    depth_resolution:
      - 480
      - 270
    depth_stabilization: 1
    fps: 30
    frame_prefix: ""
    imu_sampling_time: 2500
    local_frame: odom
    publish_tf: true
    resolution: HD720
    serial_number: -1
    streaming_adaptative_bitrate: true
    streaming_bitrate: 6000
    streaming_chunk_size: 16084
    streaming_codec: ""
    streaming_gop_size: 30
    streaming_sender_ip: ""
    streaming_sender_port: 30000
    streaming_target_fps: 30
    svo_compression: H264
    svo_file: ''
    svo_record: false
    svo_transcode_stream: false
    texture_confidence: 100
    tracking_depth_min_range: -1.0
    tracking_enable: true
    tracking_enable_area_memory: true
    tracking_enable_imu_fusion: true
    tracking_enable_pose_smoothing: true
    tracking_set_gravity_as_origin: true
    use_sim_time: false
    verbose: true
    video_sd_reliable: false
    video_sd_resolution:
      - 640
      - 360
    video_stream_hd: false
    video_stream_rate: 10
    video_stream_record_path: ""
